### ISSUE TITLE
fastQuickSort() infinite loop when arr.length = 1

### ISSUE THREAD

**Issue by SilentAntenna** [appy-one/acebase#118]
Version 1.21.5.

This happens because `shellSortBound()` loops infinitely when `start` is 0 and `end` is 1.

**Comment by appy-one** [comment]
Thanks for reporting, I'll take a look

**Comment by appy-one** [comment]
Quickly fixed this is v1.21.6

[![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing)  [![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one)
