### ISSUE TITLE
Sqlite3 not working

### ISSUE THREAD

**Issue by paradis-A** [appy-one/acebase#12]
sqlite3 not creating .sqlite3 file, only <dbname>.acebase with data.db in it.

```javascript
//index.js
const {AceBase,SQLiteStorageSettings} = require("acebase")
const db = new AceBase("mydb", new SQLiteStorageSettings({ path: "." }))
db.ready().then(()=>{
    console.log("ready")
})
```
`
{
  "name": "acesqlite3",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "acebase": "^1.0.8",
    "sqlite3": "^5.0.2"
  }
}
`

**Comment by paradis-A** [comment]
console
`
     ___          ______
    / _ \         | ___ \
   / /_\ \ ___ ___| |_/ / __ _ ___  ___
   |  _  |/ __/ _ \ ___ \/ _` / __|/ _ \
   | | | | (_|  __/ |_/ / (_| \__ \  __/
   \_| |_/\___\___\____/ \__,_|___/\___|
                       realtime database

[mydb] Database "mydb" details:
[mydb] - Type: AceBase binary
[mydb] - Record size: 128
[mydb] - Page size: 1024
[mydb] - Max inline value size: 50
[mydb] - Root record address: 0, 0
[mydb] KIT read, 0 keys indexed
[mydb] FST read, 0 pages allocated, 0 free ranges
[mydb] Node "/" is being created
[mydb] Node "/" saved at address 0,0 - 1 addresses, 4 bytes written in 1 chunk(s)
ready
`

**Comment by appy-one** [comment]
You should add the ```SQLiteStorageSettings``` to the ```storage``` property of the settings you are passing to the ```AceBase``` constructor.

The correct syntax is:
```js
const db = new AceBase("mydb", { storage: new SQLiteStorageSettings({ path: "." }) });
```

**Comment by paradis-A** [comment]
Thanks for the quick response. now it's working.
