### ISSUE TITLE
Add BigInt support

### ISSUE THREAD

**Issue by Mitsichury** [appy-one/acebase#121]
Hi :) 

I have noticed that if I add a BigInt field, I can't sort or apply filters on it.
It is rightly stored and loaded.
Could you add the support if BigInt for filtering please ? 
Could be great as JS does not handle big numbers with precision.

Thank you :)

**Comment by appy-one** [comment]
You bigints now are stored as strings in the db, that's why they don't sort ok. I'm working on bigint support now, check latest commits

**Comment by Mitsichury** [comment]
Amazing, thx a lot 👍

**Comment by appy-one** [comment]
Support for `bigint` has now been implemented and published in v1.22.0!

[![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing)  [![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one)

**Comment by Mitsichury** [comment]
Hi appy-one,
Thank you for publishing a new realese, I tried to update but it seems that add an Index on BigInt  value is not working well.
I have an error about JSON serialisation : TypeError: Do not know how to serialize a BigInt

const totalResults = await query.take(1000000).count()

I'll try to create a unit test for that.
Thanks !
