### ISSUE TITLE
Sorting is always ascending when using indexes and take()

### ISSUE THREAD

**Issue by Mitsichury** [appy-one/acebase#124]
Hi :) 

I've been through a weird behaviour when trying to sort data.
Here a TU that reproduce the issue.
Could you fix it please or tell me what do I do wrong please ? 
Thank you very much.

`
/// <reference types='@types/jasmine' />
const { DataReference, ObjectCollection } = require("acebase-core");
const { AceBase } = require("..");
const { createTempDB } = require("./tempdb");

describe("Query", () => {
    /** @type {AceBase} */
    let db;
    /** @type {{(): Promise<void>}} */
    let removeDB;

    /** @type {DataReference} */
    let moviesRef;

    afterAll(async () => {
        await removeDB();
    });

    beforeAll(async () => {
        ({ db, removeDB } = await createTempDB());
        db.indexes.create(`movies`, "name");
        db.indexes.create(`movies`, "amount");
        moviesRef = db.ref("movies");
        const entry1 = {
            id: "id1",
            name: "name",
            amount: 1,
        };
        const entry2 = {
            id: "id2",
            name: "another",
            amount: 10,
        };
        const entry3 = {
            id: "id3",
            name: "name",
            amount: 100,
        };

        const movies = [entry1, entry2, entry3];
        await moviesRef.set(ObjectCollection.from(movies));
    });

    it("error with indexes, order and take", async () => {
        const errors = await getDataBy(["name"]);
        expect(errors.getValues().map(({ id }) => id)).toEqual(["id3", "id1"]);
    });

    async function getDataBy(requestFilter) {
        const query = moviesRef.query();
        query.filter("name", "in", requestFilter);
        query.sort("amount", false);
        return await query.take(20).get();
    }
});
`

**Comment by appy-one** [comment]
Thanks for reporting, I'll take a look!

**Comment by Mitsichury** [comment]
Super fast, thank you very much ! :D

**Comment by appy-one** [comment]
I published the fix in v1.22.0!

[![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing)  [![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one)
