### ISSUE TITLE
Expose data-proxy getArrayObservable functionality

### ISSUE THREAD

**Issue by donl** [appy-one/acebase#131]
Would it be possible to make the getArrayObservable function available (from the data-proxy API)?

TIA

**Comment by appy-one** [comment]
Hi Don, it's part of the (undocumented) `OrderedCollectionProxy` which you can get from calling `getOrderedCollection` on a proxy. It's built specifically to use objects collections with a managed sort order as arrays in front-ends. How would you want to use the function?

**Comment by donl** [comment]
Ahh.  When originally reading the source code I missed that connection.  Thanks!
