### ISSUE TITLE
Acebase looks great, just added support in MeshCentral

### ISSUE THREAD

**Issue by Ylianst** [appy-one/acebase#137]
I am that main author of MeshCentral, a open-source remote management web site. [One of the community members](https://github.com/Ylianst/MeshCentral/issues/4398) point out AceBase was a good replacement for [NeDB](https://github.com/louischatriot/nedb/) that is no longer maintained. I needed a pure NodeJS database to use as a default for small instances where someone does not want to setup MongoDB, PostgreSQL, MariaDB, MySQL. AceBase looks like it works perfectly for what I need and I spent the day integrating it into MeshCentral. It will be in the next version, MeshCentral v1.0.66, when it's published.

![MC2-AceBaseSupport](https://user-images.githubusercontent.com/1319013/184524629-211ed63d-3108-4bac-b3fe-798589d3ab81.png)

Note that inline with your #100, I am making my users put `"sponsor": true` in the MeshCentral config.json to remove the banner, so basically forwarding that thru. Running MeshCentral looks like this:

![image](https://user-images.githubusercontent.com/1319013/184524731-cf5f740c-ad9f-467e-af15-0e2378eb52de.png)

Just wanted to say thank you. I still have work to do to optimize things, but so far the basics seem to work well.

**Comment by appy-one** [comment]
That's awesome, thanks!!
I'll take a look at MeshCentral 👍🏼👍🏼

**Comment by Ylianst** [comment]
I will have a video on AceBase integration with MeshCentral on my [YouTube channel](https://www.youtube.com/c/meshcentral), it will premiere on September 7th.

**Comment by Ylianst** [comment]
The video of [AceBase with MeshCentral just got published](https://www.youtube.com/watch?v=7rWBfZMYpYk).

**Comment by appy-one** [comment]
Great video @Ylianst, thanks!

**Comment by Ylianst** [comment]
Wanted to come here and say a big thank you to @appy-one. [You fixed my MeshCentral code](https://github.com/Ylianst/MeshCentral/pull/4557) and released a new version of AceBase with fixes. I am on vacation until October 18th, but can't wait to try out the new AceBase!
