### ISSUE TITLE
BigInt cache serialisation error

### ISSUE THREAD

**Issue by Mitsichury** [appy-one/acebase#141]
Hi :)
When filtering on an indexed BigInt value, it throws an error as a big int as no default way to be serialized.
The proposed solution work on serialisation but it does not work at all querying results.
I opened a draft PR with an example : https://github.com/appy-one/acebase/pull/140
Hope it can help you :)
Thank you !

**Comment by appy-one** [comment]
I'll publish a new version later today with the fix!

**Comment by appy-one** [comment]
Fix has been published in v1.24.0, let me know if it works!
Thanks again for your PR and done research!

[![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one) [![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing)
