### ISSUE TITLE
Property 'ref' does not exist on type 'AceBase'.

### ISSUE THREAD

**Issue by Tulipesz** [appy-one/acebase#145]
Hi!
I'm building a project with electron + typescript but the only types that appear for me are "ready" and "close".
Strange that the lib supports typing, I don't know what's going on.
The only way to get around the error is to add 
`// @ts-expect-error`
before the line, but it doesn't seem like the right thing to do.

![Screenshot_1](https://user-images.githubusercontent.com/43249004/187100016-c9f52348-6634-4d7f-a316-328ca24ef1aa.png)

Temporarily:

![Screenshot_2](https://user-images.githubusercontent.com/43249004/187100212-2224273b-af6a-4cc4-b4e0-e52b85e12da7.png)

Thx for the project and i appreciate any help.

**Comment by appy-one** [comment]
Where are you importing `AceBase` from?

**Comment by Tulipesz** [comment]
> Where are you importing `AceBase` from?

`import { AceBase } from 'acebase'`

**Comment by appy-one** [comment]
That looks ok. I tried reproducing today by creating a basic Electron app with TypeScript and AceBase, but everything worked as expected so there must be something else wrong in your project. Did you install acebase througn npm/yarn? And which version are you using?

**Comment by Tulipesz** [comment]
> Isso parece ok. Tentei reproduzir hoje criando um aplicativo Electron básico com TypeScript e AceBase, mas tudo funcionou como esperado, então deve haver algo mais errado em seu projeto. Você instalou o acebase através do npm/yarn? E qual versão você está usando?

Installed through yarn:
`yarn add acebase`

My package.json dependencies:
`"dependencies": {
    "acebase": "^1.23.0",
    "electron-json-storage": "^4.5.0",
    "electron-log": "^4.4.8",
    "electron-updater": "^5.2.1",
    "pdfkit": "^0.13.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.4.0",
    "react-router-dom": "^6.3.0",
    "styled-components": "^5.3.5",
    "winrawprinter": "^1.0.3"
  },
  "devDependencies": {
    "@types/electron-json-storage": "^4.5.0",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@types/styled-components": "^5.1.26",
    "@typescript-eslint/eslint-plugin": "^5.33.0",
    "@typescript-eslint/parser": "^5.33.0",
    "copy-webpack-plugin": "^11.0.0",
    "cross-env": "^7.0.3",
    "css-loader": "^6.7.1",
    "electron": "^20.0.2",
    "electron-builder": "^23.3.3",
    "eslint": "^8.22.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^3.4.1",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jest": "^26.8.2",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-react": "^7.30.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.5.0",
    "rimraf": "^3.0.2",
    "style-loader": "^3.3.1",
    "ts-loader": "^9.3.1",
    "tsconfig-paths": "^4.1.0",
    "tsconfig-paths-webpack-plugin": "^4.0.0",
    "typescript": "^4.7.4",
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0",
    "webpack-merge": "^5.8.0"
  }`

I don't really bother with problems specific to my projects, but this is very strange to me since the whole acebase project is typed.

**Comment by Tulipesz** [comment]
Inside module typing:
![Screenshot_2](https://user-images.githubusercontent.com/43249004/187275270-4e268dff-2a74-4647-a18c-265061f3acb3.png)
![Screenshot_4](https://user-images.githubusercontent.com/43249004/187275275-5aededfb-0536-48db-8c17-1310082b38e8.png)

**Comment by appy-one** [comment]
That's very strange! Can you try opening up `acebase-core/package.json` and `acebase-core/types/index.d.ts` to see if that changes anything?

**Comment by Tulipesz** [comment]
I think the problem is in tsconfig.json, acebase does not create its typing in the @types folder of node_modules.
My "typeRoots" in tsconfig.json:
![code](https://user-images.githubusercontent.com/43249004/187278776-37ef64ea-2c97-4028-a1f8-8ed2335e5a50.png)

My node_modules/@types:
![Screenshot_5](https://user-images.githubusercontent.com/43249004/187281120-366db49f-e89c-4787-acde-4818e292ac5c.png)

In the acebase-core folder all types are inside the "types" folder, how does the acebase module know that it has to get the types from this folder?

![Screenshot_6](https://user-images.githubusercontent.com/43249004/187282577-720f6068-483c-4041-9c39-33e93bdd3633.png)

**Comment by appy-one** [comment]
Why are you using `typeRoots`? Each package that has typings has a `types` entry in its `package.json` file. If it doesn't, you'd need to install a `@types/[packagename]` dependency for it (when available). Both `acebase` and `acebase-core` have their types location specified in their `package.json` so there's no need to install anything else, or to manually specify other locations. Maybe you should try commenting out / removing the `typeRoots` entry in your `tsconfig.json` and see what happens?

**Comment by Tulipesz** [comment]
Thanks a lot for the help @appy-one ! And thanks for the explanation of the `types` entry in `package.json`, I didn't know that.

The problem was in my tsconfig.json even though in the `moduleResolution` entry. As I created my project through a template (https://github.com/Devtography/electron-react-typescript-webpack-boilerplate), it already came with the `typeRoots` set (but it works with it set anyway), the problem is that the `moduleResolution` came set as `"Node16"` and according to this discussion:
https://github.com/microsoft/TypeScript/issues/49160#issuecomment-1137482639  
some libs are breaking with this `moduleResolution` when `package.json` has the `exports` entry (to be able to support cjs and esm in the same package). I just changed the `moduleResolution` entry in my `tsconfig.json` to `"Node"` and everything is working perfectly.
Again thanks a lot for the help!

**Comment by appy-one** [comment]
Thanks for your research @Tulipesz! I'm now also [generating `index.d.ts` files into the CommonJS and ESM distribution folders](https://github.com/appy-one/acebase-core/commit/6eafbbacddbbd2929e8ade671c770790dc06f7c2) that simply export all types from the right location. I've published the changes with `acebase-core` v1.22.0. After updating (reinstall `acebase` dependency), you should be able to use Node16 module resolution without issues!
