### ISSUE TITLE
Enable es6 import in Node.js

### ISSUE THREAD

**Issue by clibu** [appy-one/acebase#17]
I'm writing all my Node.js code using es6 import's however AceBase currently needs the following hack for import to work.
````
import pkg from 'acebase';
const { AceBase } = pkg;
````

**Comment by appy-one** [comment]
Why not just use
```js
import { AceBase } from 'acebase';
```

**Comment by clibu** [comment]
````
import { AceBase } from 'acebase';
         ^^^^^^^
SyntaxError: The requested module 'acebase' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can
be imported by importing the default export.
For example:
import pkg from 'acebase';
const { AceBase } = pkg;
````

**Comment by clibu** [comment]
This is using  ```"type": "module",``` in package.json

**Comment by appy-one** [comment]
I'm not able to reproduce?
If I set ```"type": "module"``` in my test package, I am able to use ```import { AceBase } from 'acebase';``` without getting an error.
What node version are your using? I just tested with v14.15.4

**Comment by appy-one** [comment]
Apparently this is possible since Node v14.13.0, see [this tweet](https://twitter.com/MylesBorins/status/1311033983824793601), or this blog post about it: [Node.js now supports named imports from CommonJS modules, but what does that mean?](https://simonplend.com/node-js-now-supports-named-imports-from-commonjs-modules-but-what-does-that-mean/)

**Comment by clibu** [comment]
I am using 14.7.0 which works fine with es6 modules.  I've just updated to 15.11.0 and import works now.  

Whether you want to try and support older versions of Node is a question for you.😀

Did you notice my discussion post: https://github.com/appy-one/acebase/discussions/13

**Comment by appy-one** [comment]
Sorry, didn't see the discussion earlier. Somehow the GitHub notification emails are not always getting through...

AceBase supports older Node versions, I haven't checked it but should at least be compatible back to version 7. If I switch to using ES modules, that would mean dropping support for older Node versions. And with the Node team already having fixed mixing CommonJS / ES modules, I'd say "don't fix it if it ain't broken"! 😄
