### ISSUE TITLE
Empty field name behavior

### ISSUE THREAD

**Issue by donl** [appy-one/acebase#172]
When `set`ing or `push`ing a key-value pair, with an empty string `""` for the `key` , an empty child node is created with the same `key` as its parent.

I doubt this is the desired behavior, but I leave that up to you.

Also, I see some quirks with creating invalid keys (eg: containing `\`) on a `acebase-client`, being cached locally and then finally failing on the `server` with some read locks.  Let me know if I should create another ticket for this.

**Comment by appy-one** [comment]
Ok, sounds like I need to be a little less permissive on what can be used as key names
