### ISSUE TITLE
.sort causes each item to be read again

### ISSUE THREAD

**Issue by meaningg** [appy-one/acebase#190]
.sort causes each item to be read from the database a second time - is it okay ?

with .sort 
![image](https://user-images.githubusercontent.com/61989272/208239938-b339f4c7-d7bc-4a00-a02d-f8bff8b21edd.png)

without .sort
![image](https://user-images.githubusercontent.com/61989272/208239951-0a2c8223-65c3-4d43-adf6-3c563e071f74.png)

**Comment by appy-one** [comment]
It's a bit hard to say without the rest of your code, but if you are using `sort` in combination with `take` and `skip`, it will first need to determine which nodes should be loaded for the result set. If you have no index on the target sort column(s), it needs to perform a "table scan" to read all sort column(s) values. Then, it will read all requested data from nodes that are in the `take` / `skip` window: those records will have effectively been read twice.

**Comment by meaningg** [comment]
Yes, I use a combination of .sort and .take. Now that explains it all. Thank you!

**Comment by appy-one** [comment]
You're welcome!

[![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing) [![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one)
