### ISSUE TITLE
Getting feature not supported error when attempting to run in Electron app

### ISSUE THREAD

**Issue by csuwildcat** [appy-one/acebase#206]
I can only get Acebase to run in Electron if I use the `AceBase.WithIndexedDB` storage option, even though Electron has full Node.js access to the file system. Is there perhaps some feature detection code that is viewing Electron only as a browser, because it contains access to both IDB and the file system?

**Comment by appy-one** [comment]
Sounds like you are using AceBase on the UI (`BrowserWindow`) thread instead of in the main (Node.js) process. Move the AceBase code into your main process (or preload.js) to store data to your local file system.

**Comment by csuwildcat** [comment]
@appy-one yeah, got it going in that env, but it led to a follow-up question: do you know of any existing uses of AceBase in Electron that show the best way to leverage the storage residing in the main Node process from the render process? I suppose IPC messaging?

**Comment by appy-one** [comment]
I don't have any experience with this myself, but I reckon Electron's IPC is indeed the easiest way to pass data back and forth

**Comment by appy-one** [comment]
Maybe even better, this is what I would do: start a local acebase-server instance in your main process and use an acebase-client in your UI thread to connect to it!

**Comment by csuwildcat** [comment]
Thank you for the suggestion, I think the server route is likely to be the easiest, so I'll try that!
