### ISSUE TITLE
Special chars in path corrupt data

### ISSUE THREAD

**Issue by younesbenallal** [appy-one/acebase#209]
Hi!
It seems that storing objects with special characters in keys corrupts data (which prevents from getting, removing or updating it).
For example, I receive french words from my users, which may contain chars like `é`. 
The issue is that it's difficult to debug since I can't retrieve objects that are corrupted.

I'm using Electron and Node. I've tried in the Npm RunKit playground, I don't have this issue.

Thanks 🙏

**Comment by appy-one** [comment]
Hi @younesbenallal thanks for reporting this. I came across some code that might have caused this issue, fix is on its way
