### ISSUE TITLE
Request: Example or test file of using acebase with username + salt + hash?

### ISSUE THREAD

**Issue by qpwo** [appy-one/acebase#60]
I think I know how to store the passwords but a good example would put me at ease. I searched password, salt, & hash in the repo and couldn't find anything.

Here's an example typescript/express/node auth server without the db, if that helps: https://gist.github.com/qpwo/4b2ae3aaaf222d099b34898152118c43

Or if you don't have time yourself I could PR a new test case

**Comment by appy-one** [comment]
You don't have to store passwords or salts or hashes anywhere in your database. You are probably searching for the `auth` functionality built into [AcebaseServer](https://github.com/appy-one/acebase-server) and [AceBaseClient](https://github.com/appy-one/acebase-client). User management is all built into the client and server code, you won't have to worry about authentication!

**Comment by qpwo** [comment]
Holy crap how did i miss that. Acebase really has the best of everything
