### ISSUE TITLE
Wildcards at index root

### ISSUE THREAD

**Issue by ThePhantomLemon** [appy-one/acebase#86]
```js
db.indexes.create("*/media", "timestamp") 
.then(() => {
    return db.query("*/media") /
      .take(100)
      .sort("timestamp", false)
      .get();
})
.then((postSnapshots) => {
      console.log(postSnapshots)
});
```
The above code returns an error from line 1095 in data-index.js. specifically this line:
```js
const wildcardValues = childPath.match(wildcardRE).slice(1);
```
`match()` is returning null so of course it errors when trying to call `slice()`.
Presumably I should have my data just be 1 level deeper.

**Comment by appy-one** [comment]
I tried to reproduce this but couldn't so I checked the code, The regular expression used expects the keys for wildcards to only contain characters A-Z, a-z, 0-9 and/or _. Do your keys maybe contain other characters than these?

**Comment by ThePhantomLemon** [comment]
Hey, so I ran all the keys through a regex and stuff to check and everything was fine. But then I decided to try the above code again and it works now. It's a possibility that when I initially ran this the database wasn't ready yet, since I refactored quite a bit since then. IDK if that would result in this kind of issue though. In any case I can't reproduce it.
